[package]
name = "emu-audio-types"
version = "0.1.0"
authors = ["ferris <jake@fusetools.com>"]
description = "Audio abstraction types for the emu project."
homepage = "https://github.com/emu-rs/emu"
repository = "https://github.com/emu-rs/emu-audio-types"
license = "BSD-2-Clause"